title: Stephen Jennings
url: "https://jennings.io" # the base hostname & protocol for your site
baseurl: "/" # the subpath of your site, e.g. /blog/
description: >
  Yet another blog from someone you've never heard of.
twitter_username: sgjennings
github_username:  jennings
github_repo_url: https://github.com/jennings/jennings.github.io

permalink: /blog/:year/:month/:title/
timezone: America/Los_Angeles
markdown: kramdown
highlighter: rouge
include:
  - ".well-known"
exclude:
  - Gulpfile.js
